name = "BallArithmetic"
uuid = "77e4f72b-b5a4-4fb0-ac2a-dcc32095a072"
version = "0.1.1"
authors = ["Luca Ferranti and Isaia Nisoli"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"
OpenBLASConsistentFPCSR_jll = "6cdc7f73-28fd-5e50-80fb-958a8875b1af"
RoundingEmulator = "5eaf0fd0-dfba-4ccb-bf02-d820a40db705"
SetRounding = "3cc68bcd-71a2-5612-b932-767ffbe40ab0"

[weakdeps]
ArbNumerics = "7e558dbc-694d-5a72-987c-6f4ebed21442"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"

[extensions]
ArbNumericsExt = "ArbNumerics"
DistributedExt = "Distributed"
DoubleFloatsExt = "DoubleFloats"
FFTExt = "FFTW"
GenericLinearAlgebraExt = "GenericLinearAlgebra"
GenericSchurExt = "GenericSchur"
IntervalArithmeticExt = "IntervalArithmetic"
MultiFloatsExt = "MultiFloats"

[compat]
ArbNumerics = "1"
Combinatorics = "1.1.0"
Coverage = "1.8.1"
DoubleFloats = "1"
FFTW = "1"
GenericLinearAlgebra = "0.3.19"
GenericSchur = "0.5"
IntervalArithmetic = "0.20.9"
JLD2 = "0.6.2"
MacroTools = "0.5"
MultiFloats = "2.3.0"
OpenBLASConsistentFPCSR_jll = "0.3.21"
RoundingEmulator = "0.2"
SetRounding = "0.2"
julia = "^1.9"

[extras]
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"
Test = "8dfed614-5729-5b62-bb73-8f89d75bee26"

[targets]
test = ["GenericLinearAlgebra", "GenericSchur", "MultiFloats", "Test"]
